# Generated by Django 4.2.5 on 2023-09-05 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/base', verbose_name='Рисунок')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рисунок',
                'verbose_name_plural': 'Рисунки',
            },
        ),
        migrations.CreateModel(
            name='ImageSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, verbose_name='Путь до картинки')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сохраненная картинка',
                'verbose_name_plural': 'Сохраненки',
            },
        ),
        migrations.CreateModel(
            name='Stih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('emotional', models.CharField(choices=[('Дипрессивные', 'Дипрессивные'), ('Любовные', 'Любовные'), ('Счастливые', 'Счастливые'), ('Пустые', 'Пустые')], max_length=255, verbose_name='Вид')),
                ('content', models.TextField(blank=True, verbose_name='Стих')),
            ],
            options={
                'verbose_name': 'Стих',
                'verbose_name_plural': 'Стихи',
            },
        ),
    ]
